### ISSUE TITLE
Microbundle 0.15.1

### ISSUE THREAD

**Issue by daniele-zurico** [developit/microbundle#1009]
I use microbundle with react and typescript.
My build command is the following:

```bash
    "build": "microbundle --jsx React.createElement --css-modules true",
```
It works perfectly fine with 0.14.x

but when I update on 0.15.x it raise the following error:

```bash
semantic error TS2304: Cannot find name 'Fragment'
```

**Comment by rschristian** [comment]
Please provide your input, else we're left guessing on how to accurately reproduce.

**Comment by daniele-zurico** [comment]
@rschristian I linked the project ... btw it's https://github.com/Capgemini/dcx-react-library

**Comment by rschristian** [comment]
You referenced this issue from another project but that's not a minimal reproduction.

Just copy/paste the input that triggers this please.

**Comment by daniele-zurico** [comment]
the full error is:
```bash
danielezurico@Danieles-MacBook-Pro dcx-react-library % yarn dev
yarn run v1.22.10
$ microbundle watch --jsx React.createElement
Watching source, compiling to dist:
(rpt2 plugin) Error: /Users/danielezurico/Documents/Projects/dcx-react-library/src/autocomplete/Autocomplete.tsx(369,5): semantic error TS2304: Cannot find name 'Fragment'.
Error: /Users/danielezurico/Documents/Projects/dcx-react-library/src/autocomplete/Autocomplete.tsx(369,5): semantic error TS2304: Cannot find name 'Fragment'.
    at error (/Users/danielezurico/Documents/Projects/dcx-react-library/node_modules/rollup/dist/shared/rollup.js:198:30)
    at throwPluginError (/Users/danielezurico/Documents/Projects/dcx-react-library/node_modules/rollup/dist/shared/rollup.js:21894:12)
    at Object.error (/Users/danielezurico/Documents/Projects/dcx-react-library/node_modules/rollup/dist/shared/rollup.js:22616:20)
    at Object.error (/Users/danielezurico/Documents/Projects/dcx-react-library/node_modules/rollup/dist/shared/rollup.js:22071:42)
    at RollupContext.error (/Users/danielezurico/Documents/Projects/dcx-react-library/node_modules/microbundle/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:20259:30)
    at /Users/danielezurico/Documents/Projects/dcx-react-library/node_modules/microbundle/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:29527:23
    at Array.forEach (<anonymous>)
    at printDiagnostics (/Users/danielezurico/Documents/Projects/dcx-react-library/node_modules/microbundle/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:29500:17)
    at Object.transform (/Users/danielezurico/Documents/Projects/dcx-react-library/node_modules/microbundle/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:29785:17)
    at /Users/danielezurico/Documents/Projects/dcx-react-library/node_modules/rollup/dist/shared/rollup.js:22825:37
```
