### ISSUE TITLE
external module not working

### ISSUE THREAD

**Issue by larafale** [developit/microbundle#232]
Hello guys, loving this project so far. after reading all the issues, still can't find why it does not work when adding an external module. my index.js file only contain 
```
import axios from 'axios'
export default {foo:'bar'}
```
but when i run
```
microbundle --output build --format cjs,umd --name myLibName --sourcemap false --external all
```

i get a syntax error on what seem to be axios dependencie babylon
```
> microbundle --output build --format cjs,umd --name myLibName --sourcemap false --external all

(flow-remove-types plugin) SyntaxError: Unexpected token, expected ; (2:9)

at undefined:2:9
SyntaxError: Unexpected token, expected ; (2:9)
    at Parser.pp$5.raise (/home/myproject/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/home/myproject/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp.semicolon (/home/myproject/node_modules/babylon/lib/index.js:1742:38)
    at Parser.pp$1.parseExpressionStatement (/home/myproject/node_modules/babylon/lib/index.js:2236:8)
    at Parser.parseExpressionStatement (/home/myproject/node_modules/babylon/lib/index.js:5934:20)
    at Parser.pp$1.parseStatement (/home/myproject/node_modules/babylon/lib/index.js:1911:17)
    at Parser.parseStatement (/home/myproject/node_modules/babylon/lib/index.js:5910:22)
    at Parser.pp$1.parseBlockBody (/home/myproject/node_modules/babylon/lib/index.js:2268:21)
    at Parser.pp$1.parseBlock (/home/myproject/node_modules/babylon/lib/index.js:2247:8)
    at Parser.pp$1.parseStatement (/home/myproject/node_modules/babylon/lib/index.js:1868:19)
```

is there something i can do about it ? thanks

**Comment by larafale** [comment]
using require instead of import does not throw an error, but the generated file (umd in particular) does not include the axios code. don't know why

**Comment by larafale** [comment]
sounds great to me :) thx a lot
