### ISSUE TITLE
Bundling Typescript/Node library not finding nodejs modules

### ISSUE THREAD

**Issue by jonathansant** [developit/microbundle#238]
I'm trying to bundle a typescript node package. I am getting the following error:

```
'child_process' is imported by src\commander\commander.ts, but could not be resolved – treating it as an external dependency
'util' is imported by src\commander\commander.ts, but could not be resolved – treating it as an external dependency
'util' is imported by src\fs\fs.ts, but could not be resolved – treating it as an external dependency
'os' is imported by src\config\config-transform.service.ts, but could not be resolved – treating it as an external dependency
Error: Could not load util (imported by C:/GitHub/odin.node.core/src/commander/commander.ts): ENOENT: no such file or directory, open 'util'
```

`package.json`:

```
{
  "name": "@odin/tools.libs",
  "version": "0.1.0",
  "description": "Odin libs for cli tools.",
  "main": "dist/index.js",
  "source": "src/index.ts",
  "umd:main": "dist/index.umd.js",
  "module": "dist/index.m.js",
  "scripts": {
    "build": "microbundle",
    "dev": "microbundle watch"
  },
  "author": "Cerberus Technology",
  "license": "ISC",
  "dependencies": {
    "chalk": "^2.4.1",
    "inversify": "^5.0.1",
    "lodash": "^4.17.11",
    "typescript": "^3.1.4"
  },
  "devDependencies": {
    "@odin/build-tools": "^0.4.0",
    "@types/lodash": "^4.14.117",
    "@types/node": "^10.12.1",
    "microbundle": "^0.7.0"
  }
}
```

`tsconfig.json`: 
```
{
  "compilerOptions": {
    "target": "es2015",
		"module": "ES2015",
		"moduleResolution": "node",
    "emitDecoratorMetadata": true,
		"experimentalDecorators": true,
		"declaration": true,
		"noImplicitReturns": true,
		"noImplicitAny": true,
		"noFallthroughCasesInSwitch": true,
		"allowUnreachableCode": false,
		"skipLibCheck": true,
		"strictNullChecks": true,
		"stripInternal": true,
		"noEmitOnError": false,
		"noUnusedLocals": true,
		"noUnusedParameters": true,
		"noImplicitUseStrict": true,
		"allowSyntheticDefaultImports": true,
		"esModuleInterop": true,
    "pretty": true,
    "types": [
			"node"
		],
		"lib": [
			"es2018",
			"es2015",
			"es6"
		],
		"baseUrl": "."
  },
  "exclude": [
		"node_modules"
	],
  "include": [
		"typings/**/*.d.ts",
		"src/**/*.ts"
	]
}
```

Can you please point out what's wrong with this setup?

**Comment by gaui** [comment]
@developit I'm also having the same problem...

```
$ yarn microbundle build --target node
yarn run v1.12.3
$ node_modules\.bin\microbundle build --target node
'child_process' is imported by src\command.ts, but could not be resolved – treating it as an external dependency
Error: Could not load child_process (imported by src/command.ts): ENOENT: no such file or directory, open 'child_process'

    at node_modules\rollup\dist\rollup.js:21723:19
    at process.internalTickCallback (internal/process/next_tick.js:77:7)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by gaui** [comment]
It works if I do:

```
yarn microbundle build --target node --external child_process,events,assert,util
```

**Comment by gaui** [comment]
Seems to be external module resolution in Rollup.
