### ISSUE TITLE
Typescript + React

### ISSUE THREAD

**Issue by thekevinscott** [developit/microbundle#241]
Hi there,

I'm trying to get a simple Typescript React component building. It's failing and I'm lost for how to troubleshoot.

Here's an example repo:

https://github.com/thekevinscott/microbundle-typescript-react

```yarn watch```

Produces:

```
yarn run v1.12.1
$ microbundle watch --format cjs --jsx react
(node:27434) Warning: N-API is an experimental feature and could change at any time.
Watching source, compiling to dist:
(rpt2 plugin) Error: /www/microbundle-typescript-react/src/index.ts(5,17): syntax error TS1161 Unterminated regular expression literal.
Error: /www/microbundle-typescript-react/src/index.ts(5,17): syntax error TS1161 Unterminated regular expression literal.
    at error (/www/microbundle-typescript-react/node_modules/rollup/dist/rollup.js:3460:30)
    at Object.error (/www/microbundle-typescript-react/node_modules/rollup/dist/rollup.js:21136:17)
    at RollupContext.error (/www/microbundle-typescript-react/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:17185:30)
    at lodash_2 (/www/microbundle-typescript-react/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:19935:23)
    at arrayEach (/www/microbundle-typescript-react/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:532:11)
    at forEach (/www/microbundle-typescript-react/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:9359:14)
    at printDiagnostics (/www/microbundle-typescript-react/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:19908:5)
    at Object.transform (/www/microbundle-typescript-react/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:21584:17)
    at /www/microbundle-typescript-react/node_modules/rollup/dist/rollup.js:20847:25
    at <anonymous>

error Command failed with exit code 1.
```

Switching `index.ts` to be `index.js` makes it work just fine.

**Comment by prichodko** [comment]
Try adding:
```bash
--entry index.ts
```

**Comment by thekevinscott** [comment]
Hey, that did it! Thank you.

**Comment by thekevinscott** [comment]
It looks like `js` files can be `js` or `jsx`; is there a way to enable `ts` files to be treated as JSX-friendly?

**Comment by prichodko** [comment]
[I don't think so.](https://www.typescriptlang.org/docs/handbook/jsx.html)

**Comment by thekevinscott** [comment]
Got it. Thanks!
