### ISSUE TITLE
Problem(s) with 0.8.0?

### ISSUE THREAD

**Issue by ianwalter** [developit/microbundle#255]
When I pull down master, yarn, yarn build, npm link, and try to run microbundle, I get:
```
/usr/local/bin/microbundle: line 1: syntax error near unexpected token `ex'
/usr/local/bin/microbundle: line 1: `function _interopDefault (ex) { return (ex && (typeof ex === 'object') && 'default' in ex) ? ex['default'] : ex; }'
```
I noticed `dist/cli.js` is missing `#!/usr/bin/env node`. Adding it and trying to run microbundle again, I get: 
```
(babel plugin) Error: Cannot find module '@babel/plugin-syntax-jsx' from '/Users/iwalter/ianwalter/vuex-reset'
Error: Cannot find module '@babel/plugin-syntax-jsx' from '/Users/iwalter/ianwalter/vuex-reset'
    at Function.module.exports [as sync] (/Users/iwalter/microbundle/node_modules/resolve/lib/sync.js:43:15)
    at resolveStandardizedName (/Users/iwalter/microbundle/node_modules/@babel/core/lib/config/files/plugins.js:101:31)
    at resolvePlugin (/Users/iwalter/microbundle/node_modules/@babel/core/lib/config/files/plugins.js:54:10)
    at loadPlugin (/Users/iwalter/microbundle/node_modules/@babel/core/lib/config/files/plugins.js:62:20)
    at createDescriptor (/Users/iwalter/microbundle/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
    at items.map (/Users/iwalter/microbundle/node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
    at Array.map (<anonymous>)
    at createDescriptors (/Users/iwalter/microbundle/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPluginDescriptors (/Users/iwalter/microbundle/node_modules/@babel/core/lib/config/config-descriptors.js:105:10)
    at alias (/Users/iwalter/microbundle/node_modules/@babel/core/lib/config/config-descriptors.js:63:49)
```
I don't have `@babel/plugin-syntax-jsx` in my project's babel config and I get the same error in a project without a babel config so there seems to be an issue with how babel was added in #252? Or am I missing something?

**Comment by ForsakenHarmony** [comment]
Yup, suspected something was wrong, sorry about that

Will try to fix asap

**Comment by ForsakenHarmony** [comment]
Did you install it globally?

**Comment by ianwalter** [comment]
I tried that, yes. Forgot to mention that I was tipped off by dependabot upgrading to 0.8.0 but the build failed: https://dev.azure.com/ianwalter/sled/_build/results?buildId=74

**Comment by spiceboi** [comment]
Happening for me too

**Comment by ForsakenHarmony** [comment]
I know

**Comment by ForsakenHarmony** [comment]
Let me know if 0.8.1 fixes it

**Comment by ianwalter** [comment]
Thanks for the quick fix!
