### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object

### ISSUE THREAD

**Issue by dandv** [developit/microbundle#364]
I'm getting this error with microbundle v0.7.0 - v0.11.0 and npm, but not with v0.6.0 or older and npm (those give #74, so microbundle seems unusable with npm)..

```
git clone git@github.com:draftbit/twitter-lite.git
cd twitter-lite
git checkout 5a8c7f96cdbce1aa6057231b326433556b35afc2
# edit package.json and change the version of microbundle to 0.11.0
npm install
```

Output:

```
npm WARN deprecated kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.

> iltorb@2.4.2 install /home/dandv/prg/twitter-lite/node_modules/iltorb
> node ./scripts/install.js || node-gyp rebuild

info looking for cached prebuild @ /home/dandv/.npm/_prebuilds/f091be-iltorb-v2.4.2-node-v67-linux-x64.tar.gz
info found cached prebuild 
info unpacking @ /home/dandv/.npm/_prebuilds/f091be-iltorb-v2.4.2-node-v67-linux-x64.tar.gz
info unpack resolved to /home/dandv/prg/twitter-lite/node_modules/iltorb/build/bindings/iltorb.node
info unpack required /home/dandv/prg/twitter-lite/node_modules/iltorb/build/bindings/iltorb.node successfully
info install Successfully installed iltorb binary!

> husky@1.3.1 install /home/dandv/prg/twitter-lite/node_modules/husky
> node husky install

husky > setting up git hooks
husky > done

> twitter-lite@0.9.3 prepare /home/dandv/prg/twitter-lite
> microbundle

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object

    at validateString (internal/validators.js:125:11)
    at Object.resolve (path.js:977:7)
    at getInput (/home/dandv/prg/twitter-lite/node_modules/microbundle/dist/microbundle.js:342:45)
    at /home/dandv/prg/twitter-lite/node_modules/microbundle/dist/microbundle.js:433:30

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! twitter-lite@0.9.3 prepare: `microbundle`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the twitter-lite@0.9.3 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dandv/.npm/_logs/2019-03-26T05_49_03_443Z-debug.log
```

**Comment by dandv** [comment]
Getting the same error with yarn:

```
$ rm -rf package-lock.json node_modules/ yarn.lock
$ yarn
yarn install v1.15.2
info No lockfile found.
[1/4] Resolving packages...
warning jest > jest-cli > prompts > kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
warning microbundle > rollup-plugin-postcss > cssnano > autoprefixer > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning microbundle > rollup-plugin-postcss > cssnano > postcss-merge-rules > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning microbundle > rollup-plugin-postcss > cssnano > postcss-merge-rules > caniuse-api > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
[2/4] Fetching packages...
info fsevents@1.2.7: The platform "linux" is incompatible with this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "microbundle > rollup-plugin-typescript2@0.19.3" has incorrect peer dependency "rollup@>=0.68.0".
[4/4] Building fresh packages...
success Saved lockfile.
$ microbundle
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object

    at validateString (internal/validators.js:125:11)
    at Object.resolve (path.js:977:7)
    at getInput (/home/dandv/prg/twitter-lite/node_modules/microbundle/dist/microbundle.js:342:45)
    at /home/dandv/prg/twitter-lite/node_modules/microbundle/dist/microbundle.js:433:30

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by maraisr** [comment]
Currently the "source" property of your `package.json` cannot be an array. If you simply:

```diff
- "source": [
-    "stream.js",
-    "twitter.js",
-],
+ "source": "stream.js",
```

will work, alternatively, remove the `source` property from your `pacakge.json`, and change your line 49 to:

```diff
- "prepare": "microbundle",
+ "prepare": "microbundle {stream,twitter}.js",
```

let me know how you go. 💯
