### ISSUE TITLE
(rpt2 plugin) TypeError: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by SolarLiner** [developit/microbundle#407]
I've got this issue when running a build from [a project of mine](https://github.com/SolarLiner/preact-bulma) (branch `release/1.2.0`) - not sure how to repro this.

```bash
$ microbundle build
(rpt2 plugin) TypeError: Cannot read property 'get' of undefined
TypeError: Cannot read property 'get' of undefined
    at getSymbol (/home/solarliner/Documents/Projets/VSCode/preact-bulma-1/node_modules/microbundle/node_modules/typescript/lib/typescript.js:31682:38)
    at getJsxLibraryManagedAttributes (/home/solarliner/Documents/Projets/VSCode/preact-bulma-1/node_modules/microbundle/node_modules/typescript/lib/typescript.js:47756:36)
    at getJsxManagedAttributesFromLocatedAttributes (/home/solarliner/Documents/Projets/VSCode/preact-bulma-1/node_modules/microbundle/node_modules/typescript/lib/typescript.js:46977:30)
    at getJsxPropsTypeFromCallSignature (/home/solarliner/Documents/Projets/VSCode/preact-bulma-1/node_modules/microbundle/node_modules/typescript/lib/typescript.js:46948:25)
    at getEffectiveFirstArgumentForJsxSignature (/home/solarliner/Documents/Projets/VSCode/preact-bulma-1/node_modules/microbundle/node_modules/typescript/lib/typescript.js:46944:70)
    at resolveJsxOpeningLikeElement (/home/solarliner/Documents/Projets/VSCode/preact-bulma-1/node_modules/microbundle/node_modules/typescript/lib/typescript.js:49726:112)
    at resolveSignature (/home/solarliner/Documents/Projets/VSCode/preact-bulma-1/node_modules/microbundle/node_modules/typescript/lib/typescript.js:49769:28)
    at getResolvedSignature (/home/solarliner/Documents/Projets/VSCode/preact-bulma-1/node_modules/microbundle/node_modules/typescript/lib/typescript.js:49792:26)
    at checkJsxOpeningLikeElementOrOpeningFragment (/home/solarliner/Documents/Projets/VSCode/preact-bulma-1/node_modules/microbundle/node_modules/typescript/lib/typescript.js:47919:27)
    at checkJsxElementDeferred (/home/solarliner/Documents/Projets/VSCode/preact-bulma-1/node_modules/microbundle/node_modules/typescript/lib/typescript.js:47483:13)
```

**Comment by developit** [comment]
I just got snagged by this in a fresh checkout + install of preact. Likely a TypeScript update.

**Comment by deftomat** [comment]
Any news on this? I'm trying to integrate Preact 10 into Angular 7, which requires TypeScript 3.2.
