### ISSUE TITLE
flow-types are causing issues

### ISSUE THREAD

**Issue by erasmuswill** [developit/microbundle#453]
react-select/async seems to be causing this.

Seems to be the sae as #379

```
(flow-remove-types plugin) SyntaxError: Unexpected token (6:3)

at undefined:6:3
SyntaxError: Unexpected token (6:3)
    at Parser.pp$5.raise (/x/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/x/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp$9.jsxParseIdentifier (/x/node_modules/babylon/lib/index.js:7029:10)
    at Parser.pp$9.jsxParseNamespacedName (/x/node_modules/babylon/lib/index.js:7040:19)
    at Parser.pp$9.jsxParseElementName (/x/node_modules/babylon/lib/index.js:7055:19)
    at Parser.pp$9.jsxParseOpeningElementAt (/x/node_modules/babylon/lib/index.js:7145:20)
    at Parser.pp$9.jsxParseElementAt (/x/node_modules/babylon/lib/index.js:7169:29)
    at Parser.pp$9.jsxParseElement (/x/node_modules/babylon/lib/index.js:7224:15)
    at Parser.parseExprAtom (/x/node_modules/babylon/lib/index.js:7236:21)
    at Parser.pp$3.parseExprSubscripts (/x//node_modules/babylon/lib/index.js:3494:19)
```

**Comment by developit** [comment]
What version of Microbundle is this happening with?

**Comment by WilhelmErasmus** [comment]
The latest version at the time. This issue was holding up production on a project with hectic deadlines so the use of components was abandoned in favour of copy-pasta between sections.

**Comment by muuvmuuv** [comment]
Getting the same here for https://github.com/muuvmuuv/gdpr-cookie-consent-banner/tree/next
