### ISSUE TITLE
Failing build: (terser plugin) Error: `sourcemap`

### ISSUE THREAD

**Issue by belozer** [developit/microbundle#472]
```json
// package.json
{
  "name": "mb",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "source": "index.js",
  "main": "dist/index.js",
  "devDependencies": {
    "microbundle": "^0.11.0"
  }
}
```

```js
// index.js
export const test = () => console.log('test')
```

```
▶ microbundle         
node-resolve: setting options.module is deprecated, please override options.mainFields instead
node-resolve: setting options.jsnext is deprecated, please override options.mainFields instead
node-resolve: setting options.module is deprecated, please override options.mainFields instead
node-resolve: setting options.jsnext is deprecated, please override options.mainFields instead
node-resolve: setting options.module is deprecated, please override options.mainFields instead
node-resolve: setting options.jsnext is deprecated, please override options.mainFields instead
    `sourcemap` is not a supported option

(terser plugin) Error: `sourcemap` is not a supported option
DefaultsError: `sourcemap` is not a supported option
    at a.get (/home/sergey/Sandbox/microbundle/node_modules/terser/dist/bundle.min.js:1:525)
    at reportError (/home/sergey/Sandbox/microbundle/node_modules/jest-worker/build/child.js:75:11)
    at execMethod (/home/sergey/Sandbox/microbundle/node_modules/jest-worker/build/child.js:93:5)
    at process.on (/home/sergey/Sandbox/microbundle/node_modules/jest-worker/build/child.js:40:7)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:762:12)
    at _combinedTickCallback (internal/process/next_tick.js:142:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
```

**Comment by Meemaw** [comment]
Getting same error

**Comment by cheuksing** [comment]
same

**Comment by omnidan** [comment]
I had the same issue with 0.11.0, then I upgraded to the latest release `0.12.0-next.6` - it seems to work there.
