### ISSUE TITLE
Build failed when using specific dependencies

### ISSUE THREAD

**Issue by KatSick** [developit/microbundle#53]
Here is demo with reproduce.
I'm build my library that depends on multiple packages, that i want to be bundled with my lib.

https://github.com/KatSick/microbundle-mlr-issue

You need to run:

```
yarn
yarn build
```

and see error:

```
(node:11685) UnhandledPromiseRejectionWarning: Error: 'Component' is not exported by node_modules/react/index.js
    at error (/Users/ochervak/Projects/Self/microbundle-mlr-issue/node_modules/rollup/dist/rollup.js:170:15)
    at Module.error (/Users/ochervak/Projects/Self/microbundle-mlr-issue/node_modules/rollup/dist/rollup.js:17170:9)
    at missingExport (/Users/ochervak/Projects/Self/microbundle-mlr-issue/node_modules/rollup/dist/rollup.js:16843:12)
    at Module.trace (/Users/ochervak/Projects/Self/microbundle-mlr-issue/node_modules/rollup/dist/rollup.js:17253:17)
    at ModuleScope.findVariable (/Users/ochervak/Projects/Self/microbundle-mlr-issue/node_modules/rollup/dist/rollup.js:14344:28)
    at Node.Identifier.bindNode (/Users/ochervak/Projects/Self/microbundle-mlr-issue/node_modules/rollup/dist/rollup.js:11993:40)
    at NodeBase.bind (/Users/ochervak/Projects/Self/microbundle-mlr-issue/node_modules/rollup/dist/rollup.js:11007:14)
    at /Users/ochervak/Projects/Self/microbundle-mlr-issue/node_modules/rollup/dist/rollup.js:11013:56
    at /Users/ochervak/Projects/Self/microbundle-mlr-issue/node_modules/rollup/dist/rollup.js:11027:66
    at Array.forEach (<anonymous>)
```

**Comment by KatSick** [comment]
Probably we can expose `namedExports` in package.json to avoid this issue ? https://github.com/reactjs/react-redux/issues/643#issuecomment-285008041

**Comment by developit** [comment]
Hmm - it seems a pity to have to add configuration just because React isn't exporting things properly...

**Comment by KatSick** [comment]
@developit agreed. i avoid this using `--external all`, so i think, issue can be closed

**Comment by FezVrasta** [comment]
Hi I'm having the exact same problem but `--external all` doesn't help, is there a different workaround available?
