### ISSUE TITLE
imports within try blocks are hoisted incorrectly

### ISSUE THREAD

**Issue by dcastil** [developit/microbundle#639]
### Problem

Microbundle hoists a `require()` call out of a `try {}` block in a dependency. When that `require()` call throws, it is not caught by the `try {}` block anymore.

I'm not sure whether this is an issue with microbundle or rollup. A solution to this would be to not hoist `require()` calls if they are in a nested block.

### How to reproduce

Make sure you have `yarn` installed globally, then run following commands:

```sh
mkdir bug-test
cd bug-test
yarn add microbundle esm
echo "import 'esm'" > test.js
yarn microbundle test.js --format cjs --target node
node dist
```

### Expected behaviour

Commands above should execute and exit without error code.

### Actual behaviour

The `node dist` command throws this error:

```
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module '/Users/dany/code/test/bug-test/dist'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

The reason for this error is that there is this codeIn the `esm` module:

```js
[…] function q(e){let t;try{const{internalBinding:n}=require("internal/bootstrap/loaders"),r=n("natives");x(r,e)&&(t=r[e])}catch(e){}return"string"==typeof t?t:""} […]

// Simplified:
try { require("internal/bootstrap/loaders") } catch (e) {}
```

which is modified to this by microbundle in `dist/index.js`:

```js
[…] var loaders = _interopDefault(require('internal/bootstrap/loaders')); […] function q(e){let t;try{const{internalBinding:n}=loaders,r=n("natives");x(r,e)&&(t=r[e]);}catch(e){}return "string"==typeof t?t:""} […]

// Simplified:
var loaders = require("internal/bootstrap/loaders")
try { loaders } catch (e) {}
```

### Additional info

microbundle v0.12.0
Node v12.17.0
Mac OS 10.15.5
Related: https://github.com/nodejs/node/issues/33656

**Comment by marvinhagemeister** [comment]
Thanks for the detailed bug report 🎉

That's a tough one as there is no correct way to transform that code to esm without leading to unexpected and incorrect behaviour. `microbundle` is built on the assumption that the source is authored in esm. We ship with `@rollup/plugin-commonjs` by default to make a best effort to be able to bundle npm packages that don't have an esm entry.

In your particular example there is no valid equivalent in esm, because esm has no synchronous inline requires. The package you're trying to bundle (`esm`) is very special in that regard as it needs to patch in some error handling around each require call. I'm not sure if even other bundlers are able to bundle it correctly.

One might assume that only specifying `cjs` as a format has some special code paths for that, but I'm not aware of any rollup plugin that does that. All in all `microbundle` is an opiniated rollup preset in a nutshell and we rely on existing rollup plugins.

**Comment by dcastil** [comment]
Hmmm yeah that seems like a tough edge case. I'm trying to bundle a VS Code extension (which is essentially a NodeJS app) that needs to evaluate specific ES6 modules in the editor workspace at runtime. Probably that's too far of what `microbundle` was built for, the transform of commonjs dependencies to esm isn't necessary in my case.

**Comment by marvinhagemeister** [comment]
It's a bug in one of our dependencies. I'm sure the rollup folks can easily fixed it when they're made aware of it :+1:
