### ISSUE TITLE
(babel plugin) Error: [BABEL] .value is not a valid Plugin property

### ISSUE THREAD

**Issue by mirceanis** [developit/microbundle#657]
I'm seeing this error when updating microbundle from 0.11 to 0.12

```

(babel plugin) Error: [BABEL] /home/circleci/project/src/resolver.ts: .value is not a valid Plugin property

Error: [BABEL] /home/circleci/project/src/resolver.ts: .value is not a valid Plugin property
    at Object.keys.forEach.key (/home/circleci/project/node_modules/@babel/core/lib/config/validation/plugins.js:52:56)
    at Array.forEach (<anonymous>)
    at validatePluginObject (/home/circleci/project/node_modules/@babel/core/lib/config/validation/plugins.js:50:20)
    at instantiatePlugin (/home/circleci/project/node_modules/@babel/core/lib/config/full.js:209:55)
    at cachedFunction (/home/circleci/project/node_modules/@babel/core/lib/config/caching.js:33:19)
    at loadPluginDescriptor (/home/circleci/project/node_modules/@babel/core/lib/config/full.js:200:10)
    at config.plugins.reduce (/home/circleci/project/node_modules/@babel/core/lib/config/full.js:69:20)
    at Array.reduce (<anonymous>)
    at recurseDescriptors (/home/circleci/project/node_modules/@babel/core/lib/config/full.js:67:38)
    at loadFullConfig (/home/circleci/project/node_modules/@babel/core/lib/config/full.js:108:6)
```

In case it helps, here's the project where this error manifests:
https://github.com/decentralized-identity/did-resolver/pull/31

**Comment by wardpeet** [comment]
Hey, could you run `yarn why @babel/core` or `npm ls @babel/core`? I had this issue when multiple babel-core versions were installed.

**Comment by mirceanis** [comment]
This is my result. running `npm ls @babel/core`
```
├─┬ jest@26.0.1
│ └─┬ @jest/core@26.0.1
│   ├─┬ @jest/reporters@26.0.1
│   │ └─┬ istanbul-lib-instrument@4.0.3
│   │   └── @babel/core@7.10.2
│   ├─┬ @jest/transform@26.0.1
│   │ └── @babel/core@7.5.5
│   └─┬ jest-config@26.0.1
│     └── @babel/core@7.5.5  deduped
└─┬ microbundle@0.12.0
  └── @babel/core@7.10.2
```

It looks like there are 2 versions `7.10.2` from `microbundle` & `7.5.5` from `jest`
Do you have a suggestion for a workaround?

**Comment by mirceanis** [comment]
Progress report:
I used `yarn install --flat` and forced `@babel/core` to a single version.
It works now but it feels very hacky.
I don't know of a way to accomplish the same result with `npm` so this workaround doesn't work for people that don't want to switch to yarn

**Comment by developit** [comment]
As a workaround that's fine, but I agree this is an issue. My guess is that this is related to Jest 26 (recently released).

**Comment by developit** [comment]
@mirceanis FWIW I believe this might be caused by using `ts-jest` instead of `babel-jest` + `@babel/preset-typescript`. I spent about an hour debugging and I can't really pin this down to anything other than "one of these plugins doesn't work with Babel 7.5" :(

**Comment by wardpeet** [comment]
@developit I had the same issue a few weeks ago. When running `npx microbundle ` it worked but inside the monorepo it didn't. What I saw was that babel package S weren't flattened

**Comment by developit** [comment]
@wardpeet I wonder if there's something we're doing wrong when massaging the configuration:

https://github.com/developit/microbundle/blob/afafa6d2138fdcbfcde5da0655f0b89fb06e7d5b/src/lib/babel-custom.js#L14-L37
