### ISSUE TITLE
Autoprefixer MODULE_NOT_FOUND error

### ISSUE THREAD

**Issue by slikts** [developit/microbundle#683]
Following the install instructions results in an error message.

Minimal example repo: https://github.com/slikts/microbundle-test

Error message.
```
> microbundle-test@1.0.0 build /home/slikts/work/microbundle-test
> microbundle

internal/modules/cjs/loader.js:548
  throw e;
  ^

Error: Package exports for '/home/slikts/work/microbundle-test/node_modules/colorette' do not define a valid '.' target
    at resolveExportsTarget (internal/modules/cjs/loader.js:545:13)
    at applyExports (internal/modules/cjs/loader.js:459:14)
    at resolveExports (internal/modules/cjs/loader.js:508:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:577:20)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:879:27)
    at Function.Module._load (internal/modules/cjs/loader.js:785:27)
    at Module.require (internal/modules/cjs/loader.js:956:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/slikts/work/microbundle-test/node_modules/autoprefixer/lib/autoprefixer.js:5:17)
    at Module._compile (internal/modules/cjs/loader.js:1063:30) {
  code: 'MODULE_NOT_FOUND'
}
```

**Comment by marvinhagemeister** [comment]
@slikts That repo link returns a 404 for me. Did you forget to make it public by chance?

**Comment by slikts** [comment]
Sorry, the repo got published as private by default, I've made it public now.

I've tried downgrading to the few previous versions and also installing `autoprefixer` and `colorette` as peer dependencies, and it's had no effect, the error stays the same.

**Comment by slikts** [comment]
The issue was with node 13.1.0 and the `exports` `package.json` field used by `cxolorette`. Upgrading node resolves it.
