### ISSUE TITLE
(babel plugin) TypeError: C:\...\index.js: id.split is not a function

### ISSUE THREAD

**Issue by sneyed** [developit/microbundle#696]
Related: https://github.com/developit/microbundle/issues/258

# steps to repro
1. yarn init -y
2. yarn add microbundle react react-dom
3. Add this `index.js`
```
import React from "react";

const Component = () => {
  return <div>hi</div>;
};

export default Component;
```
4. Add these lines to `package.json`
```
"main": "dist/index.js",
"module": "dist/index.modern.js",
"source": "index.js",
"scripts": {
    "bundle": "microbundle --no-compress --format modern,cjs --jsx"
  }
```
5. yarn bundle

# output

```
C:\dev\repo\test  (test@1.0.0)
λ yarn bundle
yarn run v1.22.4
$ microbundle --no-compress --format modern,cjs --jsx
(babel plugin) TypeError: C:\dev\repo\test\index.js: id.split is not a function
TypeError: C:\dev\repo\test\index.js: id.split is not a function
    at C:\dev\repo\test\node_modules\@babel\plugin-transform-react-jsx\lib\transform-classic.js:32:15
    at Object.post (C:\dev\repo\test\node_modules\@babel\plugin-transform-react-jsx\lib\transform-classic.js:48:47)
    at buildElementCall (C:\dev\repo\test\node_modules\@babel\helper-builder-react-jsx\lib\index.js:145:12)
    at PluginPass.exit (C:\dev\repo\test\node_modules\@babel\helper-builder-react-jsx\lib\index.js:34:24)
    at newFn (C:\dev\repo\test\node_modules\@babel\traverse\lib\visitors.js:175:21)
    at NodePath._call (C:\dev\repo\test\node_modules\@babel\traverse\lib\path\context.js:55:20)
    at NodePath.call (C:\dev\repo\test\node_modules\@babel\traverse\lib\path\context.js:42:17)
    at NodePath.visit (C:\dev\repo\test\node_modules\@babel\traverse\lib\path\context.js:101:8)
    at TraversalContext.visitQueue (C:\dev\repo\test\node_modules\@babel\traverse\lib\context.js:112:16)
    at TraversalContext.visitSingle (C:\dev\repo\test\node_modules\@babel\traverse\lib\context.js:84:19)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

# versions
Windows 10
yarn 1.22.4
npm 6.14.5
node v12.18.2

# dependencies
"microbundle": "^0.12.3"
"react": "^16.13.1"
"react-dom": "^16.13.1"

**Comment by sneyed** [comment]
Ah, I did not understand the docs correctly
`--jsx            A custom JSX pragma like React.createElement (default: h)`

In step 4 above instead of:
`"bundle": "microbundle --no-compress --format modern,cjs --jsx"`
I should have used:
`"bundle": "microbundle --no-compress --format modern,cjs --jsx React.createElement"`

This resolves the issue for me
