### ISSUE TITLE
"Property name expected type of string but got null" error happends in a trivial program

### ISSUE THREAD

**Issue by simnalamburt** [developit/microbundle#704]
It is obvious that it is an error of babel plugin, not Microbundle, but I can't find which plugin is the problem, so I will register an issue here.

### How to reproduce error
Execute this script in an empty directory
```bash
#!/bin/bash

cat > package.json <<< '{"devDependencies":{"microbundle":"0.12.3"}}'
cat > index.js <<'EOF'
function* one() { yield 1 }
export function* two() {
  const { value } = one().next()
  yield value
}
EOF

yarn
yarn microbundle --target=node
```

### Expected result
```console
Build "bla" to dist:
        415 B: bla.js.gz
        352 B: bla.js.br
```

### Actual result
```
WARN  missing package.json "name" field. Assuming "b".
(babel plugin) TypeError: /home/simnalamburt/workspace/b/index.js: Property name expected type of string but got null
TypeError: /home/simnalamburt/workspace/b/index.js: Property name expected type of string but got null
    at validate (/home/simnalamburt/workspace/b/node_modules/@babel/types/lib/definitions/utils.js:160:13)
    at Object.validate (/home/simnalamburt/workspace/b/node_modules/@babel/types/lib/definitions/utils.js:229:7)
    at validateField (/home/simnalamburt/workspace/b/node_modules/@babel/types/lib/validators/validate.js:24:9)
    at validate (/home/simnalamburt/workspace/b/node_modules/@babel/types/lib/validators/validate.js:17:3)
    at builder (/home/simnalamburt/workspace/b/node_modules/@babel/types/lib/builders/builder.js:38:27)
    at Object.identifier (/home/simnalamburt/workspace/b/node_modules/@babel/types/lib/builders/generated/index.js:340:31)
    at /home/simnalamburt/workspace/b/node_modules/regenerator-transform/lib/hoist.js:32:29
    at Array.forEach (<anonymous>)
    at varDeclToExpr (/home/simnalamburt/workspace/b/node_modules/regenerator-transform/lib/hoist.js:29:23)
    at exit (/home/simnalamburt/workspace/b/node_modules/regenerator-transform/lib/hoist.js:51:20)
```

![image](https://user-images.githubusercontent.com/4435445/90591614-89fa4d00-e21e-11ea-817a-df5fcc3be0f9.png)

**Comment by simnalamburt** [comment]
Current workaround: don't desturct the result of generator.

```js
function* one() { yield 1 }
export function* two() {
  const value = one().next().value
  yield value
}
```

**Comment by developit** [comment]
Interesting. I opened #707 to turn off regenerator when bundling for Node, since we target Node 8 and it supports both generators and async functions. Hoping that fixes this issue.
