### ISSUE TITLE
TS7016: Could not find a declaration file for module

### ISSUE THREAD

**Issue by AndyOGo** [developit/microbundle#807]
Linting is okay, but the TS build with `microbundle` fails 🤔 

I have a `/types` directory with two definition files and they are configured to be used by tsc with `typeRoots`.

https://github.com/AndyOGo/stylelint-declaration-strict-value/tree/master/types

https://github.com/AndyOGo/stylelint-declaration-strict-value/blob/7f9475d9f701ac9a1657f33b1f59aa184ab9727a/tsconfig.build.json#L8

```sh
> microbundle --tsconfig tsconfig.build.json --compress

(rpt2 plugin) Error: /home/travis/build/AndyOGo/stylelint-declaration-strict-value/src/index.ts(3,22): semantic error TS7016: Could not find a declaration file for module 'shortcss'. '/home/travis/build/AndyOGo/stylelint-declaration-strict-value/node_modules/shortcss/lib/index.js' implicitly has an 'any' type.

  Try `npm install @types/shortcss` if it exists or add a new declaration (.d.ts) file containing `declare module 'shortcss';`

Error: /home/travis/build/AndyOGo/stylelint-declaration-strict-value/src/index.ts(3,22): semantic error TS7016: Could not find a declaration file for module 'shortcss'. '/home/travis/build/AndyOGo/stylelint-declaration-strict-value/node_modules/shortcss/lib/index.js' implicitly has an 'any' type.

  Try `npm install @types/shortcss` if it exists or add a new declaration (.d.ts) file containing `declare module 'shortcss';`

    at error (/home/travis/build/AndyOGo/stylelint-declaration-strict-value/node_modules/rollup/dist/shared/node-entry.js:5400:30)

    at throwPluginError (/home/travis/build/AndyOGo/stylelint-declaration-strict-value/node_modules/rollup/dist/shared/node-entry.js:11878:12)

    at Object.error (/home/travis/build/AndyOGo/stylelint-declaration-strict-value/node_modules/rollup/dist/shared/node-entry.js:12912:24)

    at Object.error (/home/travis/build/AndyOGo/stylelint-declaration-strict-value/node_modules/rollup/dist/shared/node-entry.js:12081:38)

    at RollupContext.error (/home/travis/build/AndyOGo/stylelint-declaration-strict-value/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:17194:30)

    at /home/travis/build/AndyOGo/stylelint-declaration-strict-value/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:24958:23

    at arrayEach (/home/travis/build/AndyOGo/stylelint-declaration-strict-value/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:534:11)

    at forEach (/home/travis/build/AndyOGo/stylelint-declaration-strict-value/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:9360:14)

    at printDiagnostics (/home/travis/build/AndyOGo/stylelint-declaration-strict-value/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:24931:5)

    at Object.transform (/home/travis/build/AndyOGo/stylelint-declaration-strict-value/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:27374:17)
```

https://travis-ci.com/github/AndyOGo/stylelint-declaration-strict-value/builds/218179712#L2578-L2593

**Comment by AndyOGo** [comment]
Meanwhile I disabled [`noImplicitAny`](https://www.typescriptlang.org/tsconfig#noImplicitAny) just for the build.

https://github.com/AndyOGo/stylelint-declaration-strict-value/pull/148/files

**Comment by AlexTilha** [comment]
The same issue, please fix.

**Comment by cloverhearts** [comment]
same issue ;D

**Comment by rschristian** [comment]
This looks to be an upstream issue in rpt2 as far as I can tell, doesn't seem to acknowledge `typeRoots`.

**Comment by rschristian** [comment]
Pushed #888, hopefully that provides enough instruction to help avoid this issue.

If not, feel free to comment suggestions on that PR so that we can improve it.
