### ISSUE TITLE
[BUG] (babel plugin) SyntaxError: /Users/chudong/workBench/xxx/audio_track.ts: Unable to handle nested super.prop usage

### ISSUE THREAD

**Issue by DyncMark** [developit/microbundle#835]
[os]: 
- macOS Catalina 10.15.4
- nodejs v14.4.0
- microbundle 0.13.0

[error log]:
```

$ microbundle
(babel plugin) SyntaxError: /Users/chudong/workBench/xxxxx/src/tracks/microphone_audio_track.ts: Unable to handle nested super.prop usage
  42 |         return new Promise(async (resolve, reject) => {
  43 |             if (unClose) {
> 44 |                 super.setEnabled(enabled);
     |                 ^^^^^^^^^^^^^^^^
  45 |                 resolve();
  46 |                 return;
  47 |             }
SyntaxError: /Users/chudong/workBench/xxxxx/src/tracks/microphone_audio_track.ts: Unable to handle nested super.prop usage
  42 |         return new Promise(async (resolve, reject) => {
  43 |             if (unClose) {
> 44 |                 super.setEnabled(enabled);
     |                 ^^^^^^^^^^^^^^^^
  45 |                 resolve();
  46 |                 return;
  47 |             }
    at File.buildCodeFrameError (/Users/chudong/workBench/xxxxx/node_modules/@babel/core/lib/transformation/file/file.js:240:12)
    at NodePath.buildCodeFrameError (/Users/chudong/workBench/xxxxx/node_modules/@babel/traverse/lib/path/index.js:138:21)
    at hoistFunctionEnvironment (/Users/chudong/workBench/xxxxx/node_modules/@babel/traverse/lib/path/conversion.js:194:27)
    at NodePath.arrowFunctionToExpression (/Users/chudong/workBench/xxxxx/node_modules/@babel/traverse/lib/path/conversion.js:105:23)
    at PluginPass.ArrowFunctionExpression (/Users/chudong/workBench/xxxxx/node_modules/@babel/preset-modules/lib/plugins/transform-async-arrows-in-class/index.js:37:14)
    at newFn (/Users/chudong/workBench/xxxxx/node_modules/@babel/traverse/lib/visitors.js:175:21)
    at NodePath._call (/Users/chudong/workBench/xxxxx/node_modules/@babel/traverse/lib/path/context.js:55:20)
    at NodePath.call (/Users/chudong/workBench/xxxxx/node_modules/@babel/traverse/lib/path/context.js:42:17)
    at NodePath.visit (/Users/chudong/workBench/xxxxx/node_modules/@babel/traverse/lib/path/context.js:92:31)
    at TraversalContext.visitQueue (/Users/chudong/workBench/xxxxx/node_modules/@babel/traverse/lib/context.js:116:16)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by developit** [comment]
Interesting! This is actually a bug in [@babel/preset-modules](https://github.com/babel/preset-modules/blob/6155d0ddd2ba47d1d325659989e80e8a659d0e13/src/plugins/transform-async-arrows-in-class/index.js#L31).

Here's the bug [reproduced in the Babel repl](https://babeljs.io/repl#?browsers=edge%3E%3D16%2Csafari%3E%3D10.1&build=&builtIns=false&corejs=3.6&spec=false&loose=true&code_lz=MYGwhgzhAEBiD29oFMAeAXZA7AJjAQmAE7QDeAUNNMPFhOkQK7DrxEAUAlGZVdBIwAOyDpwDcvKpOhZkAd2gAFIvAC2ASwjJ2kAJ5Zg0EgF4AfDz58BwogDoAZoi4TLVdfejsGjZN1Eu-AF9xXkDyQKA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.14.3&externalPlugins=).
