### ISSUE TITLE
NPE occured when typescript plugin goes to wrong

### ISSUE THREAD

**Issue by mycoin** [developit/microbundle#934]
version: 0.13.3

error details:
```
(rpt2 plugin) Error: /Users/apple/Workspace/Odts/starter-sdk/src/index.ts(13,16): semantic error TS2552: Cannot find name 'StarterSdk2s'. Did you mean 'StarterSdk'?
Error: /Users/apple/Workspace/Odts/starter-sdk/src/index.ts(13,16): semantic error TS2552: Cannot find name 'StarterSdk2s'. Did you mean 'StarterSdk'?
    at error (/Users/apple/Zend/bundle-scripts/node_modules/rollup/dist/shared/rollup.js:161:30)
    at throwPluginError (/Users/apple/Zend/bundle-scripts/node_modules/rollup/dist/shared/rollup.js:21832:12)
    at Object.error (/Users/apple/Zend/bundle-scripts/node_modules/rollup/dist/shared/rollup.js:22557:20)
    at Object.error (/Users/apple/Zend/bundle-scripts/node_modules/rollup/dist/shared/rollup.js:22009:42)
    at RollupContext.error (/Users/apple/Zend/bundle-scripts/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:17237:30)
    at /Users/apple/Zend/bundle-scripts/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:25033:23
    at arrayEach (/Users/apple/Zend/bundle-scripts/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:545:11)
    at Function.forEach (/Users/apple/Zend/bundle-scripts/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:9397:14)
    at printDiagnostics (/Users/apple/Zend/bundle-scripts/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:25006:12)
    at Object.transform (/Users/apple/Zend/bundle-scripts/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:29275:17)

TypeError: Cannot read property 'then' of undefined
    at WatchEmitter.<anonymous> (/Users/apple/Zend/bundle-scripts/node_modules/microbundle/dist/microbundle.js:720:29)
    at WatchEmitter.emit (events.js:314:20)
    at Watcher.run (/Users/apple/Zend/bundle-scripts/node_modules/rollup/dist/shared/watch.js:163:22)
```
For compatibility with exceptions:
<img width="787" alt="image" src="https://user-images.githubusercontent.com/1845440/157370103-18180e33-8222-45c1-a460-ee95af9dbab6.png">

**Comment by rschristian** [comment]
Closing as fixed in #935
