### ISSUE TITLE
Question: How to use dynamic ES imports (creating multiple exports)

### ISSUE THREAD

**Issue by bestow-jd** [developit/microbundle#987]
I'm attempting to use dynamic ES imports
```js
if (someCondition) {
  import("./dynamicImport.js");
}
```
However, since this creates multiple chunks when bundling, it gives this error.
```bash
$ microbundle-crl --no-compress --format modern,cjs
Error: You must set "output.dir" instead of "output.file" when generating multiple chunks.

    at error (/Users/jdfrancis/Desktop/Bestow/design-system/node_modules/microbundle-crl/node_modules/rollup/dist/shared/node-entry.js:5400:30)
    at normalizeOutputOptions (/Users/jdfrancis/Desktop/Bestow/design-system/node_modules/microbundle-crl/node_modules/rollup/dist/shared/node-entry.js:14128:20)
    at getOutputOptionsAndPluginDriver (/Users/jdfrancis/Desktop/Bestow/design-system/node_modules/microbundle-crl/node_modules/rollup/dist/shared/node-entry.js:13910:32)
    at Object.write (/Users/jdfrancis/Desktop/Bestow/design-system/node_modules/microbundle-crl/node_modules/rollup/dist/shared/node-entry.js:13983:63)
    at /Users/jdfrancis/Desktop/Bestow/design-system/node_modules/microbundle-crl/dist/microbundle.js:431:49
```
How can I change this setting under the hood?

**Comment by rschristian** [comment]
Seems like you're having an issue with `microbundle-crl`. `micrrobundle-crl` is a fork, and not this repository. You can find it [here](https://github.com/probablyup/microbundle).

Your example works just fine in microbundle proper.

**Comment by bestow-jd** [comment]
Oh sorry! My fault

**Comment by rschristian** [comment]
No worries! That package does (unfortunately) point to this repo (rather than its own), so it's a really common mix up (we even have a label for it).

That fork is quite unmaintained; depending on the features you use, migrating to `microbundle` could be beneficial. The main difference (as far as I understand, anyhow) is that we do less asset handling and focus more on the JS.
